on: push

jobs:
  git-test:
    runs-on: macos-latest

    steps:
      - name: Run a one-line script
        run: git clone https://github.com/Marcono1234/git-file-length-test .

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
