on: push

jobs:
  git-test:
    runs-on: macos-latest

    steps:
      - name: git clone
        run: git clone https://github.com/Marcono1234/git-file-length-test .
        # Ignore exit code; see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
        shell: bash {0}

      - run: git status
        
      - name: git restore
        # Run the restore command suggested by Git
        run: git restore --source=HEAD :/
        
      - run: git status
